kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-react-electron-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-react-electron-app
  template:
    metadata:
      labels:
        app: sample-react-electron-app
    spec:
      containers:
        - name: sample-react-electron-app
          image: thesolotraveller/sample-react-electron-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: sample-react-electron-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32767my0w
  selector:
    app: sample-react-electron-app